create table public.waitlist (
  id bigint generated by default as identity not null,
  email text not null,
  created_at timestamp with time zone not null default now(),
  constraint waitlist_pkey primary key (id),
  constraint waitlist_email_key unique (email)
) TABLESPACE pg_default;