export const tableMock = [
  {
    id: 1,
    rowNumber: "#1",
    icon: "down",
    iconColor: "red.500",
    date: "Jun 13, 2025",
    category: "Plans",
    account: "BBVA credit card",
    type: "Expense",
    notes: "",
    amount: "100",
    options: null,
  },
  {
    id: 2,
    rowNumber: "#2",
    icon: "down",
    iconColor: "red.500",
    date: "Jun 13, 2025",
    category: "Plans",
    account: "BBVA credit card",
    type: "Expense",
    notes: "",
    amount: "200",
    options: null,
  },
  {
    id: 3,
    rowNumber: "#3",
    icon: "down",
    iconColor: "red.500",
    date: "Jun 13, 2025",
    category: "Plans",
    account: "BBVA credit card",
    type: "Expense",
    notes: "",
    amount: "300",
    options: null,
    is_enabled: false,
  },
  {
    id: 4,
    rowNumber: "#4",
    icon: "up",
    iconColor: "cyan.500",
    date: "Jun 13, 2025",
    category: "Plans",
    account: "BBVA credit card",
    type: "Expense",
    notes: "",
    amount: "400",
    options: null,
  },
];
